---
title: "TRACER analysis TCGA survival"
format: html
editor: visual
---

```{r}
#| label: load-packages
#| include: false
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggpubr)
  library(ggsci)
  library(readxl)
  library(DESeq2)
  library(ComplexHeatmap)
  library(BiocParallel)
  library(GSVA)
  library(survival)
  library(survminer)
  library(forestplot)
  library(ggVennDiagram)
  })
```


# load TCGA clinical data from 2018 Cell paper

```{r}
tcga.clin <- read_excel("NIHMS978596-supplement-1.xlsx", sheet = "TCGA-CDR",
                        na = c("", "[Not Available]", "[Not Applicable]", "[Unknown]")) 
```

```{r}
paad.clin <- tcga.clin |> filter(type == "PAAD")
rm(tcga.clin)
```

```{r}
table(paad.clin$gender)
table(paad.clin$race)
table(paad.clin$ajcc_pathologic_tumor_stage)
table(paad.clin$clinical_stage)
table(paad.clin$histological_type)
table(paad.clin$histological_grade)
table(paad.clin$treatment_outcome_first_course)
```

# load TCGA expression data

```{r}
PAAD.mRNA <- readRDS("./data/TCGA/TCGA_rse_v2.rds")
```

```{r}
head(colnames(PAAD.mRNA))
head(rownames(PAAD.mRNA))
head(names(colData(PAAD.mRNA)))
```

## remove non PDAC samples

```{r}
sample_correct <- read_xlsx("./meta/TCGA_PAAD/cancers-411370-Table S1.xlsx", skip = 1)
  
keep_sample <- sample_correct[sample_correct[,3] == "PDAC",1][[1]]
keep_sample <- keep_sample[!is.na(keep_sample)]
  
samples_to_keep <- unlist(sapply(keep_sample, function(k) grep(k, PAAD.mRNA$gdc_cases.samples.submitter_id, value=T)))
  
PAAD.mRNA <- PAAD.mRNA[,PAAD.mRNA$gdc_cases.samples.submitter_id %in% samples_to_keep]
table(PAAD.mRNA$gdc_cases.samples.sample_type)
#table(PAAD.mRNA$gdc_cases.samples.submitter_id)
#colnames(PAAD.mRNA) <- PAAD.mRNA$gdc_cases.samples.submitter_id
head(colnames(PAAD.mRNA))

rm(keep_sample, samples_to_keep, sample_correct)
```

## normalize expression

```{r}
PAAD.dds <- DESeqDataSetFromMatrix(countData = PAAD.mRNA@assays$data$counts,
                                   colData = colData(PAAD.mRNA),
                                   design = ~ gdc_cases.samples.submitter_id)
PAAD.dds <- vst(PAAD.dds)
```

```{r}
PAAD.mRNA.vst <- PAAD.dds@assays@data@listData[[1]]
colnames(PAAD.mRNA.vst) <- PAAD.mRNA$gdc_cases.samples.submitter_id
PAAD.mRNA.vst[1:5, 1:5]
```

```{r}
rm(PAAD.dds)
rm(PAAD.mRNA)
```

## update gene names from ENSEMBL ID to gene symbols

```{r}
grch38 <- annotables::grch38
```

```{r}
head(rownames(PAAD.mRNA.vst))
head(grch38$ensgene)
head(grch38$symbol)
grep("ENSG00000000003", grch38$ensgene, value = T)
grep("ENSG00000000003", rownames(PAAD.mRNA.vst), value = T)

length(intersect(gsub("\\.[1-9]|\\.[1-9][1-9]", "", rownames(PAAD.mRNA.vst)), grch38$ensgene))
```

```{r}
rownames(PAAD.mRNA.vst) <- gsub("\\.[1-9]|\\.[1-9][1-9]", "", rownames(PAAD.mRNA.vst))

PAAD.mRNA.vst <- PAAD.mRNA.vst[intersect(rownames(PAAD.mRNA.vst), grch38$ensgene),]
```

```{r}
rownames(PAAD.mRNA.vst) <- plyr::mapvalues(rownames(PAAD.mRNA.vst),
                                           from = grch38$ensgene,
                                           to = grch38$symbol, 
                                           warn_missing = F)

head(rownames(PAAD.mRNA.vst))
table(is.na(rownames(PAAD.mRNA.vst)))

rm(grch38)
```

## transpose exprs matrix

```{r}
PAAD.mRNA.vst <- PAAD.mRNA.vst |> 
  t() |> 
  as.data.frame()
```

## remove duplicated genes

```{r}
length(names(PAAD.mRNA.vst))
length(unique(names(PAAD.mRNA.vst)))

PAAD.mRNA.vst <- subset(PAAD.mRNA.vst, select=which(!duplicated(names(PAAD.mRNA.vst))))
```

## remove non expressed genes

```{r}
hist(colSums(PAAD.mRNA.vst))
table(apply(PAAD.mRNA.vst, 2, function(a) length(unique(a))==1))

PAAD.mRNA.vst <- PAAD.mRNA.vst[,!apply(PAAD.mRNA.vst, 2, function(a) length(unique(a))==1)]
```

## rownames (sample IDs) to column

```{r}
PAAD.mRNA.vst <- PAAD.mRNA.vst |>
  rownames_to_column("bcr_patient_barcode")

PAAD.mRNA.vst %>% select(where(is.character))
```

## estimate classical/basal

```{r}
paad.purist.subtype <- read_csv("Purist-TCGA-moffitt-calls.csv")
```

```{r}
paad.purist.subtype <- paad.purist.subtype |>
  mutate(bcr_patient_barcode = substr(ID, 1, 12))
```

```{r}
length(intersect(paad.clin$bcr_patient_barcode, paad.purist.subtype$bcr_patient_barcode))
```

```{r}
paad.clin <- left_join(paad.clin, paad.purist.subtype, by="bcr_patient_barcode")
```

# survival analysis

## epi geneset survival analysis

```{r}
genesets.epi <- readRDS("./genesets_epithelial_for_UCell_new.rds")

# a 20241023 patch for the genesets
holder28.1 <- readRDS("MC_TRACER_ONLY_NEGATIVE_TOP_200_GENE_dataframe.rds")
holder27.1 <- readRDS("MC_TRACER_ONLY_POSITIVE_TOP_200_GENE_dataframe.rds")
genesets.epi$MC_TRACER_ONLY_NEGATIVE <- holder28.1$gene.name
genesets.epi$MC_TRACER_ONLY_POSITIVE <- holder27.1$gene.name

genes.basal <- c("VGLL1", "S100A2", "LY6D", "SPRR3", "SPRR1B", "LEMD1", "KRT15", "CTSV", "DHRS9", "AREG", "CST6", "SERPINB3", "KRT6C", "KRT6A", "SERPINB4", "FAM83A", "SCEL", "FGFBP1", "KRT7", "KRT17", "GPR87", "TNS4", "SLC2A1", "KRT5")

genes.classical <- c("BTNL8", "FAM3D", "PRR15L", "AGR3", "CTSE", "LINC00675", "LYZ", "TFF2", "TFF1", "ANXA10", "LGALS4", "PLA2G10", "CEACAM6", "VSIG2", "TSPAN8", "ST6GALNAC1", "AGR2", "TFF3", "CYP3A7", "MYO1A", "CLRN3", "KRT20", "CDH17", "SPINK4", "REG4", "GATA6")

genesets.epi$Basal_like <- genes.basal
genesets.epi$Classical <- genes.classical

rm(holder27.1, holder28.1)
```

```{r}
gsva.es <- gsva(expr = PAAD.mRNA.vst %>% column_to_rownames("bcr_patient_barcode") %>% as.matrix() %>% t(),
                gset.idx.list = genesets.epi[grepl("POSITIVE|TRACER_ONLY_NEGATIVE|CC_TRACER_NEGATIVE|MC_ONLY_TRACER_NEGATIVE|Moffitt|HYPOXIA|Basal|Classical", 
                                                   names(genesets.epi))],
                method = "gsva",
                kcdf = "Poisson",
                verbose = T,
                BPPARAM = MulticoreParam(16)) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("bcr_patient_barcode")
```

```{r}
paad.clin.for.plotting <- paad.clin
cox.list <- list()
cox.gsva.list <- list()
p_list <- list()

for (gs in grep("POSITIVE|TRACER_ONLY_NEGATIVE|CC_TRACER_NEGATIVE|MC_ONLY_TRACER_NEGATIVE|Moffitt|HYPOXIA|Basal|Classical", names(genesets.epi), value = T)) {
  if (length(genesets.epi[[gs]]) == 0) next
  # Take the mRNA data
  PAAD.mRNA.vst.geneset <- PAAD.mRNA.vst %>% 
    # then make it a tibble (nice printing while debugging)
    as_tibble() %>% 
    # then get just a few genes
    select(bcr_patient_barcode, all_of(intersect(names(.), genesets.epi[[gs]]))) %>% 
    # then trim the barcode (see head(clin), and ?substr)
    mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) %>%
    # then z-scale the expressions
    mutate(across(where(is.numeric), scale)) %>%
    # then sum/mean over genes
    mutate(sum = rowSums(across(where(is.numeric))), 
           mean = rowMeans(across(where(is.numeric)))) %>%
    # then get GSVA/ssGSEA enrichment scores
    mutate(gsva = gsva.es[[gs]]) %>%
    # get high/low exprs
    mutate(Geneset_status = ifelse(mean > median(mean), "high", "low"),
           Geneset_status_gsva = ifelse(gsva > median(gsva), "high", "low")) %>%
    # subset to wanted columns
    select(bcr_patient_barcode, sum, mean, gsva, Geneset_status, Geneset_status_gsva)
  
  # then join back to clinical data
  paad.clin.geneset <- inner_join(PAAD.mRNA.vst.geneset, paad.clin, by = "bcr_patient_barcode")
  
  names(PAAD.mRNA.vst.geneset) <- c("bcr_patient_barcode", paste0(gs, "_sum"), paste0(gs, "_mean"), paste0(gs, "_gsva"), paste0(gs, "_status"), paste0(gs, "_status_gsva"))
  paad.clin.for.plotting <- inner_join(PAAD.mRNA.vst.geneset, paad.clin.for.plotting, by = "bcr_patient_barcode")
  
  if (grepl("Moffitt", gs)) {
    #gs <- "Basal/Classical"
    paad.clin.geneset <- paad.clin.geneset[!is.na(paad.clin.geneset$PurIST),]
  }
  
  # further remove samples with missing/not useful information
  paad.clin.geneset <- paad.clin.geneset[!is.na(paad.clin.geneset$OS.time),]
  #paad.clin.geneset <- paad.clin.geneset[paad.clin.geneset$PurIST == "Classical",]
  #paad.clin.geneset <- paad.clin.geneset[paad.clin.geneset$OS.time <= 1500,]
  
  if (grepl("Basal", gs)) {
    paad.clin.geneset.basal <- paad.clin.geneset[!is.na(paad.clin.geneset$PurIST),]
  }
  if (grepl("Classical", gs)) {
    paad.clin.geneset.classical <- paad.clin.geneset[!is.na(paad.clin.geneset$PurIST),]
  }
  
  # fit CoxPH model
  paad.clin.geneset$mean.dicho <- plyr::mapvalues(paad.clin.geneset$Geneset_status,
                                                  from = c("high", "low"),
                                                  to = c(1, 0))
  cox1 <- coxph(Surv(OS.time, OS) ~ mean.dicho, data = paad.clin.geneset)
  cox2 <- coxph(Surv(OS.time, OS) ~ gsva, data = paad.clin.geneset)
  cox.list[[gs]] <- cox1
  cox.gsva.list[[gs]] <- cox2
  
  sfit1 <- survfit(Surv(OS.time, OS) ~ Geneset_status, data = paad.clin.geneset)
  sfit2 <- survfit(Surv(OS.time, OS) ~ Geneset_status_gsva, data = paad.clin.geneset)
  
  
  if (grepl("Moffitt", gs)) {
    sfit3 <- survfit(Surv(OS.time, OS) ~ PurIST #+ Macrophage_status_gsva.y
                     ,
                     data = paad.clin.geneset)
  }
  #summary(sfit, times=seq(0,365*5,365))
  
  if (grepl("Moffitt", gs)) {
    gs <- "Basal/Classical"
    
    ggsurvplot_list(list(sfit3), data = paad.clin.geneset,
                    surv.median.line = "hv",
                    legend.title = list("Expression"),
                    legend.labs = list(c("Gene group expression > Median", "Gene group expression < Median")),
                    palette = c("#E7B800", "#2E9FDF"),
                    conf.int = FALSE, pval = TRUE, risk.table = FALSE, title = paste0("Epithelial - ", gs)) %>% print()
    
    p_list <- c(p_list,
                ggsurvplot_list(list(sfit3), data = paad.clin.geneset,
                                surv.median.line = "hv",
                                legend.title = list("Expression"),
                                legend.labs = list(c("Gene group expression > Median", "Gene group expression < Median")),
                                palette = c("#E7B800", "#2E9FDF"),
                                conf.int = FALSE, pval = TRUE, risk.table = FALSE, title = paste0("Epithelial - ", gs)))
  } else {
    ggsurvplot_list(list(sfit1, sfit2), data = paad.clin.geneset,
                    surv.median.line = "hv",
                    legend.title = list("Expression", "GSVA"),
                    legend.labs = list(c("Gene group expression > Median", "Gene group expression < Median"),
                                        c("Gene group GSVA score > Median", "Gene group GSVA score < Median")),
                    palette = c("#E7B800", "#2E9FDF"),
                    conf.int = FALSE, pval = TRUE, risk.table = FALSE, title = paste0("Epithelial - ", gs),
                    facet.by = "PurIST") %>% print()
    
    p_list <- c(p_list,
                ggsurvplot_list(list(sfit1, sfit2), data = paad.clin.geneset,
                                surv.median.line = "hv",
                                legend.title = list("Expression", "GSVA"),
                                legend.labs = list(c("Gene group expression > Median", "Gene group expression < Median"),
                                                    c("Gene group GSVA score > Median", "Gene group GSVA score < Median")),
                                palette = c("#E7B800", "#2E9FDF"),
                                conf.int = FALSE, pval = TRUE, risk.table = FALSE, title = paste0("Epithelial - ", gs),
                                facet.by = "PurIST"))
  }
}
```

```{r}
ggplot(paad.clin.geneset.basal, aes(x = PurIST, y = gsva)) + 
  geom_boxplot() + 
  labs(y = "Basal GSVA")
ggplot(paad.clin.geneset.classical, aes(x = PurIST, y = gsva)) + 
  geom_boxplot() + 
  labs(y = "Classical GSVA")
```

```{r}
pdf("figure-s7a-right.pdf", width = 5.5, height = 4)
print(p_list[[27]]$plot +
        labs(title = "Curated Hypoxia") +
        scale_colour_manual(labels = c("Gene set expression > Median", "Gene set expression < Median"), values = c("#E7B800", "#2E9FDF")) +
        guides(colour = guide_legend(nrow = 2))
      )
dev.off()

pdf("figure-s7a-left.pdf", width = 5.5, height = 4)
print(p_list[[37]]$plot +
        labs(title = "Basal-like") +
        scale_colour_manual(labels = c("Gene set expression > Median", "Gene set expression < Median"), values = c("#E7B800", "#2E9FDF")) +
        guides(colour = guide_legend(nrow = 2))
      )
dev.off()
```

```{r}
#png("test-survival-TCGA-OS-all-new-nosplit-CC_TRACER_ONLY_NEGATIVE-exprs.png", width = 6, height = 4, units = "in", res = 360)
pdf("figure-6b-left.pdf", width = 5.5, height = 4)
print(p_list[[11]]$plot +
        labs(title = "Co-culture: TRACER ONLY NEGATIVE") +
        scale_colour_manual(labels = c("Gene set expression > Median", "Gene set expression < Median"), values = c("#E7B800", "#2E9FDF")) +
        guides(colour = guide_legend(nrow = 2))
      )
dev.off()

#png("test-survival-TCGA-OS-all-new-nosplit-MC_TRACER_ONLY_NEGATIVE-exprs.png", width = 6, height = 4, units = "in", res = 360)
pdf("figure-6b-right.pdf", width = 5.5, height = 4)
# p_list[[33]] after 20241023 patch, there was a time it is p_list[[37]]
print(p_list[[33]]$plot +
        labs(title = "Monoculture: TRACER ONLY NEGATIVE") +
        scale_colour_manual(labels = c("Gene set expression > Median", "Gene set expression < Median"), values = c("#E7B800", "#2E9FDF")) +
        guides(colour = guide_legend(nrow = 2))
      )
dev.off()
```

```{r}
rm(p_list)
```

```{r}
cox.single.genes.list <- list()

# Take the mRNA data
PAAD.mRNA.vst.single.genes.coxph <- PAAD.mRNA.vst %>% 
  # then make it a tibble (nice printing while debugging)
  as_tibble() %>% 
  # then get just a few genes
  select(bcr_patient_barcode, all_of(intersect(names(.), genesets.epi$CC_TRACER_ONLY_NEGATIVE))) %>% 
  # then trim the barcode (see head(clin), and ?substr)
  mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) %>%
  # then z-scale the expressions
  mutate(across(where(is.numeric), scale))

single.genes <- names(PAAD.mRNA.vst.single.genes.coxph |> select(where(is.numeric)))

# then join back to clinical data
paad.clin.single.genes.coxph <- inner_join(PAAD.mRNA.vst.single.genes.coxph, paad.clin, by = "bcr_patient_barcode")

# further remove samples with missing/not useful information
paad.clin.single.genes.coxph <- paad.clin.single.genes.coxph[!is.na(paad.clin.single.genes.coxph$OS.time),]

# fit CoxPH model
for (gene in single.genes) {
  if(grepl("-", gene)) next
  cox.single.genes.list[[gene]] <- coxph(as.formula(paste0("Surv(OS.time, OS) ~ ", gene)), data = paad.clin.single.genes.coxph)
}
rm(gene, single.genes, PAAD.mRNA.vst.single.genes.coxph)
```

```{r}
# Extract data from cox.single.genes.list
univ_results <- lapply(cox.single.genes.list, function(x){ 
  x <- summary(x)
  p.value <- x$waldtest["pvalue"]
  wald.test <- x$waldtest["test"]
  beta <- x$coefficients[1] #coefficient beta
  HR <- x$coefficients[2] #exp(beta)
  HR.confint.lower <- x$conf.int[,"lower .95"]
  HR.confint.upper <- x$conf.int[,"upper .95"]
  HR <- paste0(HR, " (", HR.confint.lower, "-", HR.confint.upper, ")")
  res<-c(beta, HR, wald.test, p.value)
  names(res)<-c("beta", "HR (95% CI for HR)", "wald.test", 
                "p.value")
  return(res)
})
res.cox <- t(as.data.frame(univ_results, check.names = FALSE))
res.cox <- as.data.frame(res.cox)
rm(univ_results)

res.cox <- res.cox |>
  mutate(p.value = as.numeric(p.value)) |>
  mutate(p.adj = p.adjust(p.value, method = "fdr")) |>
  mutate(HR = str_split(res.cox$`HR (95% CI for HR)`, " ", simplify = T)[,1] |> as.numeric()) |>
  rownames_to_column("gene") #|>
  #mutate(celltype = str_split(signature, "\\.", simplify = T)[,1]) |>
  #mutate(signature = str_split(signature, "\\.", simplify = T)[,2])
```

```{r}
res.cox |>
  #filter(grepl("", gene)) |>
ggplot(aes(x = reorder(gene, HR), y = HR)) +
  geom_bar(stat = "identity", aes(fill = -log(p.adj))) +
  scale_fill_viridis_c() +
  labs(x = NULL, y = "Single-gene hazard ratio") +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_text(aes(label = ifelse(p.adj < 0.05, "*", "")), 
            position = position_dodge(width = .9), vjust = -.1, size = 20 / .pt) +
  theme_pubr() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 8, face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.position = c(0.5, 0.8),
        legend.direction = "horizontal") + 
  guides(alpha = guide_legend(nrow = 1, byrow = TRUE))
#ggsave("test-tcga-coxph-HR-CC_TRACER_ONLY_NEGATIVE-new.png", width = 18, height = 6, units = "in", dpi = 360)
ggsave("figure-s7c.pdf", width = 18, height = 6, units = "in")
```

```{r}
# check basal probability vs CC_TRACER_ONLY_NEGATIVE enrichment in TCGA
paad.clin.for.plotting |>
  filter(!is.na(PurIST)) |>
ggplot(aes(x = PurIST.basal.prob, y = CC_TRACER_ONLY_NEGATIVE_mean)) + 
  geom_point(aes(color = PurIST)) + 
  stat_smooth(method = "lm") +
  stat_cor(method = "spearman") +
  labs(x = "PurIST estimated basal probability",
       y = "CC_TRACER_ONLY_NEGATIVE - Expression score",
       color = "PurIST label") +
  theme_pubr() + 
  guides(color = guide_legend(nrow = 2))
#ggsave(paste0("test-clinical-assciation-TCGA-", "PAAD", "-PurIST-new-scatterplot.png"), device = "png", width = 3.5, height = 4.5, units = "in", dpi = 360)
ggsave(paste0("figure-6d-left.pdf"), device = "pdf", width = 3.5, height = 4.5, units = "in")

ggVennDiagram(genesets.epi[c(8, 
                             #28, 29, 
                             53)]) + 
  viridis::scale_fill_viridis(option = "C")

ggvenn(#genesets.epi[c(52, 53, 8)],
       list(`Basal-like` = genes.basal, `Classical` = genes.classical, CC_TRACER_ONLY_NEGATIVE = genesets.epi$CC_TRACER_ONLY_NEGATIVE),
       fill_color = pal_npg("nrc")(3),
       show_elements = F,
       show_percentage = T,
       #stroke_size = 0.5, 
       #set_name_size = 4,
       text_size = 5
       )
#ggsave(paste0("test-clinical-assciation-TCGA-", "PAAD", "-PurIST-new-venndiagram.png"), device = "png", width = 5, height = 7, units = "in", dpi = 360)
ggsave("figure-6d-right.pdf", device = "pdf", width = 5, height = 7, units = "in")
```

```{r}
# Extract data from cox.list
univ_results <- lapply(cox.list, function(x){ 
  x <- summary(x)
  p.value <- x$waldtest["pvalue"]
  wald.test <- x$waldtest["test"]
  beta <- x$coefficients[1] #coefficient beta
  HR <- x$coefficients[2] #exp(beta)
  HR.confint.lower <- x$conf.int[,"lower .95"] |> as.numeric()
  HR.confint.upper <- x$conf.int[,"upper .95"] |> as.numeric()
  HR <- paste0(HR, " (", HR.confint.lower, "-", HR.confint.upper, ")")
  res<-c(beta, HR, wald.test, p.value, HR.confint.lower, HR.confint.upper)
  names(res)<-c("beta", "HR (95% CI for HR)", "wald.test", "p.value", "lower", "upper")
  return(res)
})
res.cox <- t(as.data.frame(univ_results, check.names = FALSE))
res.cox <- as.data.frame(res.cox)
rm(univ_results)

res.cox <- res.cox |>
  mutate(p.value = as.numeric(p.value)) |>
  mutate(p.adj = p.adjust(p.value, method = "fdr")) |>
  mutate(HR = str_split(res.cox$`HR (95% CI for HR)`, " ", simplify = T)[,1] |> as.numeric()) |>
  rownames_to_column("geneset") |>
  mutate(lower = as.numeric(lower)) |>
  mutate(upper = as.numeric(upper))
```

```{r}
#png("test-tcga-coxph-HR-new-new.png", width = 6.5, height = 4, units = "in", res = 360)
pdf("figure-6c.pdf", width = 6.5, height = 4)
res.cox |> 
  filter(grepl("Moffit|CURATED_HYPOXIA|TRACER_ONLY_NEGATIVE|TRACER_ONLY_POSITIVE|Basal|Classical", geneset)) |>
  arrange(desc(HR)) |>
  mutate(HR_text = sprintf("%.2f", HR),
         p.adj_text = sprintf("%.3f", p.adj))|>
  mutate(geneset = gsub("Basal_like", "Basal-like", geneset)) |>
  forestplot(mean = HR, labeltext = c(geneset, HR_text, p.adj_text),
             vertices = TRUE,
             boxsize = 0.2,
             clip = c(-Inf, 2.1),
             xlab = "Hazard ratio",
             zero = 1,
             is.summary = FALSE) |>
  fp_add_lines(h_3 = gpar(lty = 2)) |>
  fp_set_style(box = "royalblue",
               line = "darkblue",
               summary = "royalblue",
               align = "lrr") |>
  fp_add_header(geneset = c("", "Gene group"),
                HR_text = c("Hazard", "ratio"),
                p.adj_text = c("Adjusted", "p-value")) |>
  fp_set_zebra_style("#EFEFEF")
dev.off()
```

```{r}
# plot a heatmap
paad.clin.for.heatmap <- paad.clin.for.plotting |> 
  select(bcr_patient_barcode, age_at_initial_pathologic_diagnosis, 
         ajcc_pathologic_tumor_stage, histological_grade, treatment_outcome_first_course,
         PurIST.basal.prob, PurIST,
         CURATED_HYPOXIA_mean, Classical_mean, Basal_like_mean,
         CC_TRACER_ONLY_NEGATIVE_mean, MC_TRACER_ONLY_NEGATIVE_mean,
         CC_TRACER_ONLY_POSITIVE_mean, MC_TRACER_ONLY_POSITIVE_mean,
         CURATED_HYPOXIA_mean)

paad.clin.for.heatmap <- paad.clin.for.heatmap |> column_to_rownames("bcr_patient_barcode") |>
  mutate(age_at_diagnosis = age_at_initial_pathologic_diagnosis,
         stage = plyr::mapvalues(ajcc_pathologic_tumor_stage, from = c("[Discrepancy]"), to = c(NA)),
         treatment_outcome = plyr::mapvalues(treatment_outcome_first_course, from = c("[Discrepancy]"), to = c(NA)))

paad.clin.for.heatmap.mtx <- paad.clin.for.heatmap |> 
  select(CURATED_HYPOXIA_mean, Basal_like_mean, Classical_mean,
         CC_TRACER_ONLY_NEGATIVE_mean, MC_TRACER_ONLY_NEGATIVE_mean,
         CC_TRACER_ONLY_POSITIVE_mean, MC_TRACER_ONLY_POSITIVE_mean,
         CURATED_HYPOXIA_mean) |> 
  as.matrix()
colnames(paad.clin.for.heatmap.mtx) <- gsub("_mean", "", colnames(paad.clin.for.heatmap.mtx))
colnames(paad.clin.for.heatmap.mtx) <- gsub("Basal_like", "Basal-like", colnames(paad.clin.for.heatmap.mtx))
```

```{r}
#png("test-heatmap-tcga-overview.png", height = 6, width = 20, units = "in", res = 321)
pdf("figure-6a.pdf", height = 6, width = 20)
Heatmap(t(paad.clin.for.heatmap.mtx),
        width = nrow(paad.clin.for.heatmap.mtx) * unit(0.1, "in"),
        name = "Expression\nscore",
        column_title = "PAAD Samples",
        show_column_names = FALSE,
        #column_split = paad.clin.for.heatmap$PurIST,
        top_annotation = columnAnnotation(df = paad.clin.for.heatmap |> 
                                            select(age_at_diagnosis, PurIST, stage, histological_grade, treatment_outcome),
                                          annotation_label = c("Age at diagnosis", "PurIST estimated subtype", "Stage", 
                                                               "Histological grade", "Treatment outcome"),
                                          show_annotation_name = TRUE,
                                          col = list(
                                            PurIST = c(`Basal-like` = "#F3756D", `Classical` = "#0FBDC2"),
                                            treatment_outcome = c(`Complete Remission/Response` = "#b1695f", `Partial Remission/Response` = "#c1eefb", 
                                                                  `Progressive Disease` = "#5d4d42", `Stable Disease` = "#f2a000"),
                                            histological_grade = c(`G1` = "#0b7769", `G2` = "#64a108", `G3` = "#eac405", `G4` = "#b01e04"),
                                            stage = c(`Stage IA` = "#c75b50", `Stage IB` = "#54fb6a", `Stage IIA` = "#2f87c7", `Stage IIB` = "#f4cd25", `Stage III` = "#144194", `Stage IV` = "#057a29")
                                          ))) |>
  draw(heatmap_legend_side = "left", annotation_legend_side = "bottom")
dev.off()
```

